name: Push and scan dockerhub containers

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push angular
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: safidesafi/scrumboard:angular
      -
        name: Scan for vulnerabilities
        id: scan_angular
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: safidesafi/scrumboard:angular
          dockerfile: ./Dockerfile
            -
      - name: Build and push keycloak
        uses: docker/build-push-action@v2
        with:
          context: ./keycloak
          push: true
          tags: safidesafi/scrumboard:keycloak
      -
        name: Scan for vulnerabilities
        id: scan_keycloak
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: safidesafi/scrumboard:keycloak
          dockerfile: ./Dockerfile
                      -
      - name: Build and push nodejsbackend
        uses: docker/build-push-action@v2
        with:
          context: ./nodejs_backend
          push: true
          tags: safidesafi/scrumboard:nodejs_backend
      -
        name: Scan for vulnerabilities
        id: scan_nodejs_backend
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: safidesafi/scrumboard:nodejs_backend
          dockerfile: ./Dockerfile
      -
        name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
